In [8]:
import pickle
import pandas as pd
from tfidf import TFIDF

In [3]:
df = pd.read_csv('../../Dataset/Dataset Skripsi - Fix Dataset (Final).csv')
df

                                                   text              label
0                 Cepat sampaiiiiiiiiiiiiiiiiiiiiiiiiii         Pengiriman
1                      Fast response recommended seller  Layanan Pelanggan
2     Barang bagus tapi analog kiri sama kanan kalo ...             Produk
3                   keren gan Produknya buat main games             Produk
4                    mantap gan!!!!!.Barang bagus juga              Produk
...                                                 ...                ...
1019             gak nyangaka keren banget jamnya hi hi             Produk
1020              Pengiriman sangat cepat. Terima kasih         Pengiriman
1021  Pesan + bayar tgl. 07 Sep 18 jam 2 siang. Bara...  Layanan Pelanggan
1022  Packingnya keren rapi dan aman pakai bubble wr...  Layanan Pelanggan
1023  Produk kedua yang saya beli disini masih memua...             Produk

[1024 rows x 2 columns]

In [6]:
df_sample = df.sample(frac=0.8, random_state=1)
df_sample

                                                  text              label
830  Barang sudah diterima. Recommended. Lebih coco...             Produk
795  Jamnya keren banget packing rapi dan berfungsi...             Produk
495                                 mantapzzzz  jiwa               Produk
822                              Cocok dipakai bokin               Produk
859  Paketan sudah sampai dengan selamat dan aman t...         Pengiriman
..                                                 ...                ...
199                           barang cepat sampai gan.         Pengiriman
450  Barang sesuai permintaan Pengiriman cepat Than...         Pengiriman
137               sip barang normal tanpa ada masalah.             Produk
536  barang sesuai deskripsi &  pesanan. respon sel...  Layanan Pelanggan
696                             Baik bagus tepat waktu         Pengiriman

[819 rows x 2 columns]

In [9]:
tfidf = TFIDF(df_sample.text)

In [15]:
# save the model to disk
filename = 'tfidf_model.pkl'
pickle.dump(tfidf, open(filename, 'wb'))